### PR TITLE
Add _event system variable if string events enabled

### PR DESCRIPTION
**Pull request by sstiller**
Adding variable `_event` https://www.w3.org/TR/scxml/#SystemVariables
with the contents `name` and `data`. https://www.w3.org/TR/scxml/#InternalStructureofEvents
`_event.name` contains the event name as `std::string`
`_event.data` is a `boost::any` (new dependency)

The support for `_event` currently only works for string events. `_event.data` could be added to the other version of `dispatch()` later.

`_event.data` is really great to update the data model in scxml or for guard conditions for transitions.

### CODE REVIEW

**Comment by jp-embedded** [comment]
Great addition ☺️

I would prefer to use std:any instead boost:any to have a dependency on c++17 instead of boost

**Comment by sstiller** [comment]
In my targets I can only use C++14 (too old compilers).
Perhaps we can add a compiler switch.

**Comment by jp-embedded** [comment]
Yes, then both options are available. I think we should make the c++17 option the default because c++17 eventually will become more and more common. Also, we already have the c++17 dependency when using the --threadsafe option, where boost is a new one.

**Comment by sstiller** [comment]
Would you prefer
* a cmdline option for scxmlcc to specify the wanted C++ version or
* always adding `#if __cplusplus >= 201703L` to the generated code to use `boost::any` or `std::any`
Then the type changes with the used c++ version automatically, what may not be wanted by the user.

Or do you have another idea?

**Comment by jp-embedded** [comment]
I think I prefer a 'use boost instead c++17' option rather than using the ifdef, because its a matter of using/not using an external library more than enabling/disabling a feature that requires c++17

Also, it could end up with a lot of ifdefs with the other method because the threadsafe option has the same issue which also requires c++17 (this could also be implemented with boost as an alternative)

**Comment by jp-embedded** [comment]
Thanks a lot :-)

**Pull request merged**
